<h2>Featured Content</h2>
<?php if($this->featuredItems):?>
	<?php foreach($this->featuredItems as $page):?>
		<div class="featuredItem">
			<h3>
				<a href="/page/view/id/<?php echo $page->id; ?>/title/<?php echo $page->name; ?>"><?php echo $page->headline; ?></a>
			</h3>
			<p><?php echo $page->description; ?></p>
			<br style="clear:left;" />
		</div>
	<?php endforeach;?>
<?php endif;?>
<?php if($this->recentPages):?>
	<div class="recentPages">
		<h3>More Pages</h3>
		<ul>
			<?php foreach($this->recentPages as $page):?>
				<li>
					<a href="/page/view/id/<?php echo $page->id; ?>"><?php echo $page->headline;?></a>
				</li>
			<?php endforeach;?>
		</ul>
	</div>
<?php endif; ?>