<?php if($this->featuredItems):?>
	<?php foreach($this->featuredItems as $blog):?>
		<!-- box -->
		<div class="triple_top"></div><!-- triplebox top ends -->
		
		<div class="triple_middle">
			<div class="<?php echo $blog->category_id; ?>">
				<h2>
					<a href="/blog/view/id/<?php echo $blog->id; ?>/title/<?php echo $blog->name; ?>">
						<?php echo (strlen($blog->headline) < 26) ? $blog->headline : rtrim(substr($blog->headline, 0, 25)).'...'; ?>
					</a>
				</h2>
				<p>
					<?php echo (strlen($blog->description) < 135) ?  $blog->description : rtrim(substr($blog->description, 0, 134)).'...'; ?>
				</p>
				<p class="readMore">
					<a href="/blog/view/id/<?php echo $blog->id; ?>/title/<?php echo $blog->name; ?>">
						Read More...
					</a>
				</p>
			</div>
		</div><!-- triplebox middle ends -->
		
		<div class="triple_bottom"></div><!-- triplebox bottom ends -->
	<?php endforeach;?>
<?php else: ?>
    <div class="triple_top"></div><!-- triplebox top ends -->
    <div class="triple_middle">
        <p>No tutorials could be found...</p>
    </div>
    <div class="triple_bottom"></div><!-- triplebox bottom ends -->
<?php endif;?>