<h2>Manage menu items</h2>
<p>Current Menu: <?php echo $this->menu->name; ?></p>
<?php if($this->items != null):?>
	<table class="spreadsheet">
		<tr>
			<th>Links</th>
			<th>Label</th>
			<th>Page</th>
			<th>Link</th>
		</tr>
		<?php echo $this->partialLoop('partials/_menu-item-row.phtml', $this->items); ?>
	</table>
<?php else:?>
	<p>This menu does not have any items yet.</p>
<?php endif;?>
<p><a href="/menuitem/add/menuId/<?php echo $this->menu->id; ?>">Add a new item</a></p>