<?php echo '<?xml version="1.0" encoding="ISO-8859-1" ?>'?>
<?php echo $this->doctype(); ?>

<?php $this->layout()->nav = $this->action('render', 'menu', null, array('menuId'=>$this->mainMenuId)); ?>
<?php $this->layout()->adminMenu = $this->action('render', 'menu', null, array('menuId'=>$this->adminMenuId)); ?>
<?php /* $this->layout()->userForm = $this->action('index', 'user'); */ ?>

<html xmlns="http://www.w3.org/1999/xhtml">
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1" />
    <?php echo $this->headTitle(); ?>
	
	<?php echo $this->loadSkin($this->skin); ?>
	<link rel="stylesheet" href="/_css/theme/jquery-ui.css" media="screen, projection" type="text/css" />
    <?php echo $this->loadConditionalJavascript($this->jsFlag); ?>
    
</head>
<body>
	<div id="outerContainer">
		<div id="container">
			<div id="navigation">
				<?php echo $this->layout()->nav; ?>
				<form method="post" id="headerSearch" action="/search" class="navSearchForm">
					<div id="search_left"></div>
					<div style="display:inline;"><input type="text" class="search_field" name="query" id="query" value="Search..."  /></div>
					<div id="search_right"></div>
					<div style="display:inline;">
						<input name="submit" type="image" src="/_uploads/images/search_btn.png" class="search_btn" value="Go!" />
					</div>
				</form>
			</div><!-- end nav -->
			
			<div id="title">
				<h1>DevDamra - Web Development &amp; Design</h1>
			</div><!-- end title -->
			
			<div id="featured">
			
				<div class="featured_image">
					<img src="/_uploads/images/featured_image.png" alt="Featured Image" />
				</div><!-- featured image ends -->
				
				<div class="featured_text">	
					<h2><?php echo $this->welcomeContent['headline']; ?></h2>
					<?php echo $this->welcomeContent['pageContent']; ?>
					<?php if(isset($this->welcomeContent['id'])):?>
					<p class="readMore">
						<a href="/page/view/id/<?php echo $this->welcomeContent['id'];?>">
							Read More...
						</a>
					</p>
					<?php endif;?>
				</div><!-- featured text ends -->
			
			</div><!-- end featured -->
			
			<div id="mainContent">	
					
				<div id="left_content">
				
					<?php echo $this->layout()->content; ?>

				</div><!-- left content ends -->
				
				<div id="right_content">
					
					<div class="midSingle_top"></div><!-- midSingle top ends -->
					
					<div class="midSingle_middle">
						<h2><?php echo $this->homeContent['headline']; ?></h2>
						<?php echo $this->homeContent['pageContent']; ?>
						<?php if(isset($this->homeContent['id'])):?>
						<p class="readMore">
							<a href="/page/view/id/<?php echo $this->homeContent['id'];?>">
								Read More...
							</a>
						</p>
						<?php endif;?>
					</div><!-- midSingle middle ends -->
					
					<div class="midSingle_bottom"></div><!-- midSingle top ends -->
				</div><!-- right content ends -->
			</div><!-- end mainContent -->
			
			
			<div id="footer">
				<p id="copyright">&copy; <?php echo date('Y')?> philipdamra.com | Powered by Zend Framework</p>		
				<?php $auth = Zend_Auth::getInstance(); ?>
        		<?php if($auth->hasIdentity()): ?>
					<div id="admin-menu"><?php echo $this->layout()->adminMenu; ?></div>
				<?php else: ?>
					<p id="footerMenu" class="button"><a href="/user">Log In</a></p>
				<?php endif; ?>	
			</div>

			<?php /*  $this->addScriptPath(APPLICATION_PATH.'/views/scripts');
                    echo $this->render('util/profiler.phtml'); */  ?>
		</div><!-- end container -->
		
	</div><!-- end outer container -->

</body>

</html>