<?php echo '<?xml version="1.0" encoding="UTF-8" ?>'?>
<?php echo $this->doctype(); ?>
<?php $this->layout()->nav = $this->action('render', 'menu', null, array('menuId'=>$this->mainMenuId)); ?>
<?php $this->layout()->adminMenu = $this->action('render', 'menu', null, array('menuId'=>$this->adminMenuId)); ?>
<?php $this->layout()->userForm = $this->action('index', 'user'); ?>

<html>
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1">
    <?php echo $this->headTitle(); ?>
    
    <?php echo $this->loadSkin($this->skin); ?>
	<link rel="stylesheet" href="/_css/theme/jquery-ui.css" media="screen, projection" type="text/css" />
    <?php echo $this->loadConditionalJavascript($this->jsFlag); ?>
    
</head>
<body>
	<div id="outerContainer">
		<div id="container">
			<div id="navigation">
				<?php echo $this->layout()->nav; ?>
				<form method="post" id="headerSearch" action="/search" class="navSearchForm">
					<div id="search_left"></div>
					<input type="text" class="search_field" name="query" id="query" value="Search..."  />
					<div id="search_right"></div>
					<input name="submit" type="image" src="/_uploads/images/search_btn.png" class="search_btn" value="Go!" />
				</form>
			</div><!-- end nav -->
			
			<div id="title_interior">
				<h1>DevDamra - Web Development &amp; Design</h1>
			</div><!-- end title -->
			
			<div id="mainContent">	
					
				<div id="left_content_interior">
					<div class="single_top"></div><!-- singlebox top ends -->
					<div class="single_middle">
						<?php echo $this->layout()->content; ?>
					</div><!-- singlebox middle ends -->
					<div class="single_bottom"></div><!-- singlebox bottom ends -->
				</div><!-- left content ends -->
				
				<div id="right_content_interior">
					<div class="smallSingle_top"></div><!-- smallSinglebox top ends -->
					<div class="smallSingle_middle">
						<div id="categoryMenuContainer">
							<h2>Categories</h2>
							<ul id="categoryMenu">
								<li class="php"><a href="/search/index/category/php">PHP Tutorials</a></li>
								<li class="flexbuilder"><a href="/search/index/category/flex-builder">Flex Builder Tutorials</a></li>
								<li class="htmlcss"><a href="/search/index/category/html_css">HTML/CSS Tutorials</a></li>
								<li class="javascriptjquery"><a href="/search/index/category/javascript_jquery">Javascript/jQuery Tutorials</a></li>
								<li class="flash"><a href="/search/index/category/flash">Flash Tutorials</a></li>
								<li class="photoshop"><a href="/search/index/category/photoshop">Photoshop Tutorials</a></li>
							</ul>
						</div>
						<div class="divider" ></div>
						<div id="tagCloud">
							<h2>Tags</h2>
							<?php echo $this->tagCloud(); ?>
							<!-- 
							<ul class="Zend_Tag_Cloud">
								<li><a style="font-size:14px;" href="#">AIR</a></li>
								<li><a style="font-size:16px;" href="#">APIs</a></li>  
								<li><a style="font-size:12px;" href="#">Blueprint</a></li>
								<li><a style="font-size:16px;" href="#">CSS</a></li>  
								<li><a style="font-size:12px;" href="#">Email</a></li>  
								<li><a style="font-size:18px;" href="#">Flex Builder</a></li>
								<li><a style="font-size:12px;" href="#">HTML</a></li>  
								<li><a style="font-size:16px;" href="#">jQuery</a></li> 
								<li><a style="font-size:12px;" href="#">MVC</a></li>  
								<li><a style="font-size:10px;" href="#">OOP</a></li> 
								<li><a style="font-size:10px;" href="#">Photoshop</a></li>
								<li><a style="font-size:18px;" href="#">PHP</a></li>  
								<li><a style="font-size:12px;" href="#">Zend_AMF</a></li>
								<li><a style="font-size:16px;" href="#">Zend Framework</a></li>
							</ul> -->
						</div>
					</div><!-- smallSinglebox middle ends -->
					<div class="smallSingle_bottom"></div><!-- smallSinglebox bottom ends -->
				</div><!-- right content ends -->
				
			</div><!-- end mainContent -->
			
			
			<div id="footer">
				<p id="copyright">&copy; <?php echo date('Y')?> philipdamra.com | Powered by Zend Framework</p>		
				<?php $auth = Zend_Auth::getInstance(); ?>
        		<?php if($auth->hasIdentity()): ?>
					<div id="admin-menu"><?php echo $this->layout()->adminMenu; ?></div>
				<?php else: ?>
					<p id="footerMenu"><a href="/user">Log In</a></p>
				<?php endif; ?>	
			</div>
			<?php $this->addScriptPath(APPLICATION_PATH.'/views/scripts'); ?>
			<?php echo $this->render('util/profiler.phtml'); ?>
		</div><!-- end container -->
		
	</div><!-- end outer container -->

</body>

</html>