<h1>Search Results</h1>
<?php if($this->paginator):?>
    <p class="top">
        Your search for the <?php echo $this->searchType; ?>
        <em><?php echo $this->keywords; ?></em>
        returned <?php echo $this->count;?>
        result<?php echo ($this->count > 1) ? 's' : ''; ?>.
    </p>
	<div class="listContainer">
		<?php echo $this->partialLoop('search/search-list.phtml', $this->paginator); ?>
	</div>
    <?php echo $this->paginationControl($this->paginator, 'Sliding', 'partials/pagination-control.phtml')?>
<?php else:?>
	<p>Your search did not return any results.</p>
<?php endif;?>
