<tr>
	<td class="links">
		<a class="ui-state-default ui-corner-all button" href="/menu/edit/id/<?php echo $this->id; ?>">
			<span class="ui-icon ui-icon-pencil"></span>
		</a>
		<a class="ui-state-default ui-corner-all button" href="/menu/delete/id/<?php echo $this->id; ?>">
			<span class="ui-icon ui-icon-trash"></span>
		</a>
	</td>
	<td>
		<a href="/menuitem/index/menuId/<?php echo $this->id?>">Manage Menu Items</a>
	</td>
	<td><?php echo $this->name; ?></td>
</tr>