<?php 
	if($this->page_id > 0)
	{
		$page = new CMS_Content_Item_Page($this->page_id);
		$pageName = $page->name;
	}
	else 
	{
		$pageName = null;
	}
?>

<tr>
	<td class="links">
		<a class="ui-state-default ui-corner-all button" href="/menuitem/move/direction/up/id/<?php echo $this->id; ?>">
			<span class="ui-icon ui-icon-circle-arrow-n"></span>
		</a>
		<a class="ui-state-default ui-corner-all button" href="/menuitem/move/direction/down/id/<?php echo $this->id; ?>">
			<span class="ui-icon ui-icon-circle-arrow-s"></span>
		</a>
	</td>
	<td class="links">
		<a class="ui-state-default ui-corner-all button" href="/menuitem/edit/id/<?php echo $this->id; ?>">
			<span class="ui-icon ui-icon-pencil"></span>
		</a>
		<a class="ui-state-default ui-corner-all button" href="/menuitem/delete/id/<?php echo $this->id; ?>">
			<span class="ui-icon ui-icon-trash"></span>
		</a>
	</td>
	<td><?php echo $this->label; ?></td>
	<td><?php echo $this->link;?></td>
</tr>