<?php 
	if($this->page_id > 0)
	{
		$page = new CMS_Content_Item_Page($this->page_id);
		$pageName = $page->name;
	}
	else 
	{
		$pageName = null;
	}
?>

<tr>
	<td class="links">
		<a href="/menuitem/edit/id/<?php echo $this->id; ?>">Update</a>&nbsp;|&nbsp;
		<a href="/menuitem/move/direction/up/id/<?php echo $this->id; ?>">Move Up</a>&nbsp;|&nbsp;
		<a href="/menuitem/move/direction/down/id/<?php echo $this->id; ?>">Move Down</a>&nbsp;|&nbsp;
		<a href="/menuitem/delete/id/<?php echo $this->id; ?>">Delete</a>
	</td>
	<td><?php echo $this->label; ?></td>
	<td><?php echo $pageName; ?></td>
	<td><?php echo $this->link;?></td>
</tr>