<tr>
	<td class="links">
		<a class="ui-state-default ui-corner-all button" href="/page/edit/id/<?php echo $this->id; ?>">
			<span class="ui-icon ui-icon-pencil"></span>
		</a>
		<a class="ui-state-default ui-corner-all button" href="/page/delete/id/<?php echo $this->id; ?>">
			<span class="ui-icon ui-icon-trash"></span>
		</a>
	</td>
	<td><a href="/page/view/id/<?php echo $this->id; ?>"><?php echo $this->name; ?></a></td>
</tr>