<tr>
	<td class="links">
		<a class="ui-state-default ui-corner-all button" href="/user/edit/id/<?php echo $this->id; ?>">
			<span class="ui-icon ui-icon-pencil"></span>
		</a>
		<a class="ui-state-default ui-corner-all button" href="/user/delete/id/<?php echo $this->id; ?>">
			<span class="ui-icon ui-icon-trash"></span>
		</a>
	</td>
	<td><?php echo $this->last_name; ?></td>
	<td><?php echo $this->first_name; ?></td>
	<td><?php echo $this->username; ?></td>
	<td><?php echo $this->role; ?></td>
</tr>