<?php 
if($this->pageCount)
{
	//add each of the request params to url
	$params = Zend_Controller_Front::getInstance()->getRequest()->getParams();
	//remove the system params
	unset($params['module']);
	unset($params['controller']);
	unset($params['action']);
}
?>
<div class="paginationControl">
	<!-- previous page -->
	<?php if(isset($this->previous)): ?>
		<a href="<?php echo $this->url(array_merge($params, array('page'=>$this->previous))); ?>">&lt; Previous</a> |
	<?php else: ?>
		<span class="disabled">&lt; Previous</span>
	<?php endif; ?>
	
	<!-- numbered page links -->
	<?php foreach($this->pagesInRange as $page): ?>
		<?php if($page != $this->current): ?>
			<a href="<?php echo $this->url(array_merge($params, array('page'=>$page))); ?>">
				<?php echo $page; ?>
			</a> | 
		<?php else: ?>
			<?php echo $page; ?> |
		<?php endif; ?>
	<?php endforeach; ?>
	
	<!-- next page -->	
	<?php if(isset($this->next)): ?>
		<a href="<?php echo $this->url(array_merge($params, array('page'=>$this->next))); ?>">Next &gt;</a> |
	<?php else: ?>
		<span class="disabled">Next &gt;</span>
	<?php endif; ?>
</div>