<div id="viewBlog">
	<h1 class="pageHeading"><?php echo $this->blog->headline; ?></h1>
    <blockquote class="top"><?php echo $this->blog->description; ?></blockquote>
	<?php if(!empty($this->blog->image)):?>
		<img id="mainImage" src="<?php echo $this->blog->image; ?>" alt="<?php echo $this->blog->headline; ?>" />
	<?php endif;?>
	<div class="blogContent">
	<?php 
		$code = CMS_Content_Item_Blog::txtBtwnTags($this->blog->blogContent, 'code');
		$escCode = htmlentities($code);
	?>
		<?php echo str_replace($code, $escCode, $this->blog->blogContent); ?>
	</div>
</div>

<?php if(!empty($this->tags)):?>
<div style="clear:both">
	<p>Tags:
		<?php for($i=0; $i<count($this->tags); $i++):?><?php if($i > 0):?>,<?php endif;?>
					<a href="/search/index/tag/<?php echo $this->tags[$i]; ?>" class="blogTags">
					<?php echo $this->tags[$i]; ?></a><?php endfor;?>
	</p>
</div>
<?php endif; ?>
<?php if($this->blog->comments == 1):?>
<div id="commentGroup">
	<div id="comments">
		<?php if(count($this->comments) == 0):?>
			<p>No Comments Yet...</p>
		<?php else:?>
			<h2>Comments:</h2>
			<?php foreach($this->comments as $comment):?>
				<?php $n=1; ?>
				<div class="comment">
					<p><strong>Name: </strong><?php echo $comment->name; ?></p>
					<p><strong>Time: </strong><?php echo date('m/d/Y g:ia',$comment->timestamp); ?></p>
					<p class="commentContent"><?php echo $comment->content; ?></p>
					<?php if($this->admin):?>
						<p style="padding:0; margin:0 10; text-align: right;">
							<a class="button" href="/blog/delete-comment/comment_id/<?php echo $comment->id;?>/blog_id/<?php echo $this->blog->id; ?>">
								<span class="ui-icon ui-icon-trash"></span>							
							</a>
						</p>
					<?php endif;?>
				</div>
			<?php endforeach;?>
		<?php endif;?>
	</div>
	<div id="commentForm">
		<?php if($this->msg):?>
			<div class="ui-widget">
				<div style="margin-top: 20px; padding: 0pt 0.7em;" class=" ui-corner-all ui-widget-header"> 
					<p><span style="float: left; margin-right: 0.3em;" class="ui-icon ui-icon-info"></span>
					<strong><?php echo $this->msg['title']?></strong> <?php echo $this->msg['text']?></p>
				</div>
			</div>
		<?php endif;?>
		<?php if($this->error):?>
		<div class="ui-widget" style="margin-bottom: 25px;">
			<div style="padding: 0pt 0.7em; background: #B50012; border:none;" class="ui-state-error"> 
				<p><span style="float: left; margin-right: 0.3em;" class="ui-icon ui-icon-alert"></span> 
				<strong><?php echo $this->error['title']?></strong> <?php echo $this->error['text']?></p>
			</div>
		</div>
		<?php endif;?>
		<h2>Leave a Comment</h2>
		<?php echo $this->form; ?>
	</div>
</div>
<?php endif;?>