<div id="viewBlog">
	<h1><?php echo $this->blog->headline; ?></h1>
    <blockquote class="top"><?php echo $this->blog->description; ?></blockquote>
	<?php if(!empty($this->blog->image)):?>
		<img id="mainImage" src="<?php echo $this->blog->image; ?>" alt="<?php echo $this->blog->headline; ?>" />
	<?php endif;?>
	<div class="blogContent">
		<?php echo $this->blog->blogContent; ?>
	</div>
</div>

<?php if(!empty($this->tags)):?>
<div style="clear:both">
	<p>Tags:
		<?php for($i=0; $i<count($this->tags); $i++):?><?php if($i > 0):?>,<?php endif;?>
					<a href="/search/index/tag/<?php echo $this->tags[$i]; ?>" class="blogTags">
					<?php echo $this->tags[$i]; ?></a><?php endfor;?>
	</p>
</div>
<?php endif; ?>
<?php if($this->blog->comments == 1):?>
<div id="comments">
	<?php if(count($this->comments) == 0):?>
		<p>No Comments Yet...</p>
	<?php else:?>
		<h2>Comments:</h2>
		<?php foreach($this->comments as $comment):?>
			<?php $n=1; ?>
			<div class="comment">
				<p><strong>Name: </strong><?php echo $comment->name; ?></p>
				<p><strong>Time: </strong><?php echo date('m/d/Y g:ia',$comment->timestamp); ?></p>
				<p class="commentContent"><?php echo $comment->content; ?></p>
			</div>
		<?php endforeach;?>
	<?php endif;?>
</div>
<div id="commentForm">
	<h2>Leave a Comment</h2>
	<?php echo $this->form; ?>
</div>
<?php endif;?>